blank_issues_enabled: true
contact_links:
  - name: Feature Requests & Questions
    url: https://github.com/jvandenaardweg/sort-by-property/discussions
    about: Please ask and answer questions here.
